application: 
 applicationName: "review"
 space:
    enabled: true
    additionalLabels:
      kind: pr
      team: gabbar
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
    tenant: gabbar
 route:
    enabled: true
    additionalLabels:
       router: default
    port:
      targetPort: https
 configMap:
    enabled: true
    files:
    - nameSuffix: ""
      data:
        DB_NAME: "nordmartDB"
        MONGO_HOST: "review-mongodb"
        JAEGER_ENDPOINT: "http://jaeger-collector.istio-system:14268/api/traces"
 deployment:
   additionalLabels:
     appCategory: "backend"
   annotations:
   volumes: {}
   imagePullSecrets: nexus-docker-config-forked
   envFrom:
    - type: configmap
      name: ""    
   image:
     # replaced by CI pipeline
     repository: {{ IMAGE }}
     # replaced by CI pipeline     
     tag: {{ TAG }}
   resources: 
     limits:
       memory: 1Gi 
       cpu: 0.5
     requests:
       memory: 128Mi
       cpu: 0.1
   probes:
     readinessProbe:
       failureThreshold: 3
       periodSeconds: 60
       successThreshold: 1
       timeoutSeconds: 1
       initialDelaySeconds: 10
       httpGet:
         path: /health
         port: 8080
     livenessProbe:
       failureThreshold: 3
       periodSeconds: 60
       successThreshold: 1
       timeoutSeconds: 1
       initialDelaySeconds: 10
       httpGet:
         path: /health
         port: 8080
 service:
   ports:
   - port: 8080
     name: https
     targetPort: 8080
 rbac:
   create: true
   serviceAccount:
     create: true
     enabled: true
mongodb:
  resources:
   limits: 
     cpu: 100m
     memory: 128Mi
   requests: 
     cpu: 100m
     memory: 128Mi
  auth:
    enabled: false
  fullnameOverride: review-mongodb  
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
