apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: review
    appVersion: "v0.0.2"
    group: com.stakater.platform
    provider: stakater
    team: stakater
    chart: "application-0.0.31"
    release: "stakater-nordmart-review"
    heritage: "Helm"
  name: review
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: review-mongodb
  namespace: default
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-10.0.5
    app.kubernetes.io/instance: stakater-nordmart-review
    app.kubernetes.io/managed-by: Helm
secrets:
  - name: review-mongodb

